apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fip-controller
subjects:
- kind: ServiceAccount
  name: controller
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: fip-controller
  apiGroup: rbac.authorization.k8s.io
